config/routes.rb
Rails.application.routes.draw do
  devise_scope :user do
    root to: "devise/sessions#new"
  end
  devise_for :users, :controllers => { registrations: 'registrations'}
  resources :users
  resources :notes
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/note.rb
class Note < ApplicationRecord
    belongs_to :user

    validates :title, length: { maximum: 30, message: ": 30 characters is the maximum allowed" }
    validates :body, length: { maximum: 1000, message: ": 1000 characters is the maximum allowed" }

    def time_created
        self.created_at.in_time_zone('Eastern Time (US & Canada)').strftime("%A at %l:%M%P")
    end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :notes
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :email, uniqueness: { message: 'Shoot! Someone is already using this email. Is it you...?'}


  def full_name
    self.first_name + ' ' + self.last_name
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    def after_sign_in_path_for(resource)
        user_path(resource)
    end

    def after_sign_up_path_for(resource)
        user_path(resource)
    end

    def after_sign_out_path_for(resource_or_scope)
        new_user_session_path
    end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
    before_action :find_note, only: [:show, :edit, :update, :destroy]

    def index
        redirect_to user_path(current_user)
    end

    def show
    end

    def new
        @note = Note.new
    end
    
    def create
        @note = Note.new(note_params(:title, :body))

        if params[:note][:title].blank? && params[:note][:body].blank? 
            
            flash[:errors] = "Note must contain a title OR a body"
            redirect_to new_note_path
            return
        elsif params[:note][:title].blank?
            @note.title = @note.body.truncate(30)
        end
        
        @note.user = current_user
        if @note.save
            redirect_to user_path(current_user.id)
        else
            flash[:error] = @note.errors.full_messages[0]
            redirect_to new_note_path
        end
    end

    def edit
    end

    def update

        if params[:note][:title].blank? && params[:note][:body].blank? 
            flash[:error] = "Note must contain a title OR a body"
            redirect_to edit_note_path
            return
        elsif params[:note][:title].blank?
            @note.title = @note.body.truncate(30)
        end

        if @note.update(note_params(:title, :body))
          redirect_to user_path(@note.user)
        else
            flash[:error] = "Note could not be edited, please try again"
            redirect_to edit_note_path
        end
    end

    def destroy
        note = Note.find(params[:id])
        note.destroy
        redirect_to user_path(current_user)
    end

    private

    def find_note
        @note = Note.find(params[:id])
    end

    def note_params(*args)
        params.require(:note).permit(*args)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

    private

    def sign_up_params 
        params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
    end

    def account_update_params
        params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :current_password)
    end
end 

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :authenticate_user!
    before_action :find_user, only: [:show, :after_sign_in_path_for]

    def index
        @users = User.all
        render json: @users
    end

    def show
        # byebug
        @notes = Note.where(user_id: current_user.id)
        render 'show'
    end

    private

    def find_user
        @user = User.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>NoteTaker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale-1">
    <%= favicon_link_tag asset_path('note_icon.png') %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'styles.css'%>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-inverse">
        <div class="container">
          <div class="navbar-header">

          </div>
          <div id="navbar">
            <ul class="nav navbar-nav">
              <li><%= link_to 'Home', user_signed_in? ? user_path(current_user.id) : new_user_session_path %></li>
            </ul>
            <ul class="nav navbar-nav pull-right">
              <% if user_signed_in? %>
                <li><%= link_to 'New Note', new_note_path %></li>
                <li><%= link_to 'Log out', destroy_user_session_path, method: :delete %></li>
              <% else %>
                <li><%= link_to 'Log In', new_user_session_path %></li>
                <li><%= link_to 'Sign Up', new_user_registration_path %></li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <section id="main">
      <%= yield %>
    </section>
  </body>
</html>

app/views/notes/_errors.html.erb
<% if flash[:error] %>
  <div class="alert alert-danger" style="width: 500px">
    <%= flash[:error] %>
  </div>
<% end %>

app/views/notes/edit.html.erb
<div class="container new-post">
  <h3 class="display-4 text-center mt-5">How would you like to edit?</h3>
  <div id="edit-note-form">
    <%= render 'errors' %>
    
    <%= form_for @note, html: {class: "was-validated"} do |f| %>
      <div class="mt-3 mb-3">
        <%= f.text_field :title, value: @note.title, class: "form-control is-invalid" %>
      </div>

      <div class="mt-3 mb-3">
        <%= f.text_area :body, value: @note.body, class: "form-control is-invalid" %>
      </div>

      <%= f.submit "Confirm Edit", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/notes/new.html.erb
<div class="container new-note">
  <h3 class="display-4">Create your new note here!</h3>
  <div id="new-note-form">
    <%= form_for @note, html: {class: "was-validated"} do |f| %>
      <%= render 'errors' %>
      <div class="mt-3 mb-3">
        <%= f.text_field :title, placeholder: "Note Title", class: "form-control" %>
      </div>

      <div class="mt-3 mb-3">
        <%= f.text_area :body, placeholder: "Note Title", class: "form-control" %>
      </div>

      <%= f.submit "Submit Note", class: "btn btn-primary btn-lg" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<h1>Welcome <%=@user.first_name%>!</h1>
<div id="user-notes">
    <h2>Your Notes</h2>
    <div id="notes-list">
        <% if @notes.empty? %>
            <h4>You dont have any notes yet! Compose your first note <%= link_to 'here', new_note_path %>!</h4>
        <% end %>
        <% @notes.order('created_at DESC').each do |note| %>
            <div class="note"> 
                <h4 class="title"><%= note.title %> <span class="author-and-time">Created by <%= note.user.full_name %>, <%= note.time_created %></span></h4>
                <p><%= note.body %></p>
                <div class="buttons">
                    <%= button_to 'Edit Note', edit_note_path(note), method: :get, class: "bottom-buttons btn btn-primary" %>
                    <%= button_to 'Delete Note', note_path(note), method: :delete, class: "bottom-buttons btn btn-danger" %>
                </div>
            </div>
        <% end %>
    </div>
</div>